const actions = {
  SET_STATE: 'settings/SET_STATE',
  CHANGE_SETTING: 'settings/CHANGE_SETTING',
  SCREEN_RESIZE: 'settings/SCREEN_RESIZE',

  CHANGE_FORM_STATE: 'dreamMachine/CHANGE_FORM_STATE',

  SEND_DREAM_MACHINE_RESULT_TO_API:
    'dreamMachine/SEND_DREAM_MACHINE_RESULT_TO_API',
  SEND_DREAM_MACHINE_RESULT_TO_API_SUCCESS:
    'dreamMachine/SEND_DREAM_MACHINE_RESULT_TO_API_SUCCESS',
  SEND_DREAM_MACHINE_RESULT_TO_API_FAILURE:
    'dreamMachine/SEND_DREAM_MACHINE_RESULT_TO_API_FAILURE',
};

export default actions;
